import { RiskBadge } from "./StatusBadge";
import { formatDate } from "@/lib/utils";

type Assessment = {
  id: string;
  modelVersion: string;
  status: string;
  riskLevel: string | null;
  riskScore: number | null;
  confidenceScore: number | null;
  recommendation: string | null;
  explanationSummary: unknown;
  createdAt: Date | string;
  completedAt: Date | string | null;
};

export function AIRecommendationPanel({ assessment }: { assessment: Assessment | null }) {
  if (!assessment) {
    return (
      <div className="card p-4">
        <div className="font-semibold">AI assessment</div>
        <p className="text-muted text-sm mt-1">
          No AI assessment yet. Trigger an AI check to receive a risk score and recommendation.
        </p>
      </div>
    );
  }

  const explanations: string[] = Array.isArray(assessment.explanationSummary)
    ? (assessment.explanationSummary as string[])
    : [];

  return (
    <div className="card p-4 space-y-3">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="font-semibold">AI assessment</div>
        <RiskBadge level={assessment.riskLevel} />
      </div>
      <dl className="grid grid-cols-2 gap-y-2 text-sm">
        <dt className="text-muted">Recommendation</dt>
        <dd className="font-medium">{assessment.recommendation || "—"}</dd>
        <dt className="text-muted">Risk score</dt>
        <dd className="tabular-nums">{assessment.riskScore ?? "—"}</dd>
        <dt className="text-muted">Confidence</dt>
        <dd className="tabular-nums">{assessment.confidenceScore ?? "—"}</dd>
        <dt className="text-muted">Model version</dt>
        <dd className="font-mono text-xs">{assessment.modelVersion}</dd>
        <dt className="text-muted">Completed</dt>
        <dd>{formatDate(assessment.completedAt)}</dd>
      </dl>
      {explanations.length > 0 && (
        <div>
          <div className="text-sm font-medium mb-1">Explanation signals</div>
          <ul className="list-disc pl-5 text-sm text-muted space-y-1">
            {explanations.map((e, i) => (
              <li key={i}>{e}</li>
            ))}
          </ul>
        </div>
      )}
      <p className="text-xs text-faint">
        This is a mock AI signal generated by a rule-based stand-in service, not a trained ML model.
      </p>
    </div>
  );
}
